sudo: required
language: node_js
node_js:
  - "8"
  - "9"
#  - "10"
#  - "release"
#  - "tip"
addons:
  artifacts: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  #- npm run lint
  - npm run ganache
  - sleep 5
  - mv truffle-config.js truffle.js
  - truffle migrate --network development
  - npm run test/truffle 
  #- npm run unit
  - npm run e2e
  - npm run stop
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get -y install solc
  - ls
  - mkdir docs
  - solidity-docgen /home/travis/build/FriendlyUser/Vue-Dapp /home/travis/build/FriendlyUser/Vue-Dapp/contracts /home/travis/build/FriendlyUser/Vue-Dapp
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
#after_script:
#  - npm run coverage && cat coverage/lcov.info | coveralls
