sudo: required
language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install bignumber.js --save-dev
script:
  #- npm run lint
  - mv truffle-config.js truffle.js
  - npm run e2e
  - echo "Building the app and deploying to surge"
  - npm run build
  - npm install surge --save-dev
  # Skipping prompt in surge, see https://stackoverflow.com/questions/6264596/simulating-enter-keypress-in-bash-script
  - echo | ./node_modules/.bin/surge dist
  - echo "Making documentation"
  - chmod a+x downloadSolc.sh
  - ./downloadSolc.sh
  # Update Smart Contracts to Solidity 5.0
  # - sudo add-apt-repository -y ppa:ethereum/ethereum
  # - sudo apt-get update
  # - sudo apt-get -y install solc
  #- ./vueDoc.sh
  - solidity-docgen /home/travis/build/FriendlyUser/Vue-Dapp /home/travis/build/FriendlyUser/Vue-Dapp/contracts /home/travis/build/FriendlyUser/Vue-Dapp
  - cd website
  - npm install
  - npm run build
  - mv ./sidebars.json build/vue-dapp
  - cd ../
  # Consider removing docs/components
  - rm -rf docs/components
  - mv docs mddocs
  - mv mddocs website/build/vue-dapp
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: website/build/vue-dapp  # or remove this line to upload from root of repo
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    all_branches: true
